DEFAULT_TRIGGERED_AREA_PERCENT = 0.05
DEFAULT_FRAMES_TO_TRIGGER = 32
DEFFAULT_RETRIGGER_INTERVAL_SEC = 3
DEFAULT_FRAME_RESIZE = None
DEFAULT_CAPTURE_RECT_SIDE = 100
TARGET_FPS = 32 #camera max is 32, allowing max sampling considering computation time
CONF_FILE = 'conf/conf.yaml'
REBASE_INTERVAL = 60

DEFAULT_DOWNLOAD_PHOTO_FOLDER='./photos'
DEFAULT_CAPTURE_TARGET = 1 # 0=internal memory (faster) 1=SDCARD
DEFAULT_AUTOFOCUS_BEFORE_TRIGGER = True
DEFAULT_UI_PORT = 8080